server:
  port: 8082


spring:
  application:
    name: ts
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
  h2:
   console:
    enabled: true
    path: /h2
  datasource:
   url: jdbc:h2:~/test2_db 
  jpa:
   hibernate:
    ddl-auto:update
    

eureka:
  client:
    enabled: false

dekorate:
  kubernetes:
    serviceType: "NodePort"
    
